print("hello \"world\" world")
print('I\'m Trumil')
print("line A")
print("line B")
print("line A\nline B \n lineC")
print("line A\n line B")
print("line A \nline B")
print("name\tTrumil")
print("this is \ backslash")
print("this is backslash\\")
print("this is backslash\\\\")
print("hell\blo")